import { ServiceItem } from "@/components/Services/Services";

// Services Data
export const servicesData: ServiceItem[] = [
    {
        title: "Residential Water Purification",
        subtitle: "Safe Drinking Water for Your Family",
        description:
            "We offer advanced and reliable systems tailored for household use. Whether it's tap water, borewell water, or municipal supply, our systems ensure it is safe for consumption. Our range includes both conventional and modern technologies to suit diverse water conditions and preferences.",
        subhead: "Our Residential Services Include:",
        points: [
            "RO (Reverse Osmosis) Water Purifiers",
            "UV and UF Filtration Systems",
            "Multi Grade Sand Filters (MGF)",
            "Activated Carbon Filters",
            "Iron Removal Filters",
            "Water Softeners (for hard water)",
            "Alkaline Water Purifiers (RO + UV + UF + Alkaline)",
            "Rainwater Harvesting & Recharge Systems",
            "Rainwater Filtration Units",
            "Annual Maintenance Contracts (AMC)",
        ],
        subhead2: "Benefits:",
        benefits: [
            "Removes harmful contaminants",
            "Enhances taste and odor",
            "Protects appliances from scaling",
            "Ensures clean water for all uses",
            "Keeps your family safe from waterborne diseases",
            "Supports sustainable water management",
        ],
    },
    {
        title: "Commercial Water Purification",
        subtitle: "Smart Water Solutions for Businesses",
        description:
            "Businesses require large-scale and reliable purification systems to maintain health standards and operational efficiency. We provide customized high-capacity setups tailored to meet the demands of diverse commercial environments—from small offices to large factories and institutions.",
        subhead: "Our Commercial Offerings Include:",
        points: [
            "Commercial RO Plants (250 LPH — 1000+ LPH)",
            "UV Sterilizers",
            "Softening and Demineralization Plants",
            "Activated Carbon and Multi-Grade Sand Filters",
            "Water ATMs and Vending Systems",
            "Rainwater Filtration & Recharge Systems",
            "High-capacity Filtration Units for Hotels, Schools, Offices, and Factories",
        ],
        subhead2: "Industries We Serve:",
        benefits: [
            "Restaurants and Cafes",
            "Hotels and Resorts",
            "Schools, Colleges, and Universities",
            "Corporate Offices and Tech Parks",
            "Factories and Manufacturing Units",
            "Hospitals and Healthcare Centers",
            "Apartment Complexes and Gated Communities",
        ],
    },
    {
        title: "Industrial Water Treatment",
        subtitle: "Engineered for Performance and Compliance",
        description:
            "We specialize in designing, manufacturing, and maintaining high-capacity industrial water treatment systems that meet regulatory standards while optimizing performance. Our solutions are built for complex industrial processes, ensuring water reuse, waste reduction, and environmental compliance across various sectors.",
        subhead: "Our Industrial Solutions Include:",
        points: [
            "Industrial RO and UF Systems",
            "Effluent Treatment Plants (ETP)",
            "Sewage Treatment Plants (STP)",
            "Zero Liquid Discharge (ZLD) Systems",
            "Demineralized (DM) Water Plants",
            "Boiler and Cooling Tower Water Treatment",
            "Pressure Sand and Activated Carbon Filtration Units",
            "Iron, Fluoride, and Arsenic Removal Systems",
            "Rainwater Harvesting and Recharge Solutions",
            "High TDS and Brackish Water Treatment Plants",
        ],
        subhead2: "Features:",
        benefits: [
            "Custom-engineered systems for industrial demands",
            "Energy-efficient and low-maintenance designs",
            "Remote monitoring, control, and automation options",
            "Modular and scalable systems for future expansion",
            "Compliance with ISO, BIS, CPCB, and other environmental standards",
            "Robust performance in high-load and continuous operation settings",
        ],
    },
    {
        title: "Annual Maintenance & After-Sales Support",
        subtitle: "Your System, Our Responsibility",
        description:
            "We believe that great service doesn't stop after installation. Our comprehensive after-sales support ensures your system works optimally throughout its lifecycle. We prioritize customer satisfaction and long-term relationships through reliable service and timely assistance.",
        subhead: "Support Services:",
        points: [
            "Regular system checkups and scheduled maintenance visits",
            "Filter, membrane, and cartridge replacements",
            "24x7 Customer Helpline and WhatsApp Support",
            "On-site servicing and emergency repairs",
            "Preventive maintenance plans (AMC) for hassle-free performance",
            "Annual performance audit and efficiency reporting",
            "Upgrades and retrofitting of existing systems",
            "Spare parts availability and logistics support",
            "Service alerts and reminders via SMS/Email",
        ],
    },
    {
        title: "Custom Design & Consultation",
        subtitle: "Get Expert Advice for Your Water Problems",
        description:
            "Not sure what system suits your needs? Our water treatment consultants help you make informed decisions with personalized recommendations. From domestic homes to large industries, we design solutions based on real-time water quality, usage patterns, and infrastructure feasibility.",
        subhead: "Consultation Includes:",
        points: [
            "Free On-site Water Quality Testing (TDS, Hardness, Iron, pH, etc.)",
            "Site Surveys and Feasibility Analysis Reports",
            "Tailored System Design for Residential, Commercial, or Industrial Use",
            "Detailed Proposal with Technical Specifications and Cost Estimation",
            "Turnkey Installation with Civil, Plumbing, and Electrical Work",
            "System Training for Operators or Homeowners",
            "Regulatory Guidance for Water Discharge Compliance",
            "Post-commissioning performance evaluation",
            "Designs with future scalability and automation options",
        ],
    },
    {
        title: "Water Testing & Bacteria Removal",
        subtitle: "Detect. Purify. Protect.",
        description:
            "Our water testing services help identify microbial and chemical contaminants in your water supply. We use certified methods to detect harmful bacteria and ensure complete purification through advanced technologies.",
        subhead: "Testing Services:",
        points: [
            "Microbiological Testing: Total Coliform, Fecal Coliform (E. coli), Enterococci",
            "Chemical Testing: pH, Hardness, TDS, Iron, Chlorine, Nitrate, Heavy Metals",
            "Biological Indicators: Algae, Pathogens, Biofilms",
        ],
        subhead2: "Bacteria We Eliminate and Methods:",
        benefits: [
            "E. coli — causes diarrhea and vomiting",
            "Salmonella — causes typhoid and food poisoning",
            "Legionella — causes Legionnaires' disease",
            "Giardia and Cryptosporidium — causes intestinal infections",
            "Shigella — causes dysentery and fever",
            "UV Filtration — Destroys DNA of bacteria, viruses, and protozoa",
            "Ultra Filtration (UF) — Removes bacteria and cysts",
            "Reverse Osmosis (RO) — Removes chemicals and microbes",
            "Ozonation — Oxidizes microorganisms",
            "Activated Carbon and Sediment Filters — Removes chlorine, odor, and particles",
        ],
        compliance:
            "We follow BIS (Bureau of Indian Standards) and WHO norms to ensure your water meets safe consumption standards.",
    },
    {
        title: "Sustainability & Green Practices",
        subtitle: null,
        description:
            "We are committed to eco-friendly water treatment practices. Our systems are designed to minimize environmental impact while maintaining high performance. By integrating sustainable technologies, we help reduce your ecological footprint without compromising on efficiency or quality. Our goal is to support a cleaner future through responsible engineering, smart resource usage, and long-lasting solutions.",
        subhead: "Eco-Friendly Features:",
        points: [
            "Low water wastage",
            "Energy efficiency",
            "Reduced chemical usage",
            "Long life and recyclability",
            "Smart monitoring for resource optimization",
            "Eco-conscious materials and design choices",
        ],
    },
];
